"""Metadata introspection for the Whisper plugin used by cjm-ctl to generate the registration manifest.

Docs: https://cj-mills.github.io/cjm-transcription-plugin-whispermeta.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto #0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb #a37e28c1
import os
import sys
from typing import Any, Dict
from . import __version__

# %% ../nbs/meta.ipynb #12e9f5c3
def get_plugin_metadata() -> Dict[str, Any]: # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    # Fallback base path (current behavior for backward compatibility)
    base_path = os.path.dirname(os.path.dirname(sys.executable))

    # Use CJM config if available, else fallback to env-relative paths
    cjm_data_dir = os.environ.get("CJM_DATA_DIR")

    # Plugin data directory
    plugin_name = "cjm-transcription-plugin-whisper"
    if cjm_data_dir:
        data_dir = os.path.join(cjm_data_dir, plugin_name)
    else:
        data_dir = os.path.join(base_path, "data")
    
    db_path = os.path.join(data_dir, "whisper_transcriptions.db")
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)

    return {
        "name": plugin_name,
        "version": __version__,
        # T24: non-empty description required by the substrate validator (SG-6 / V1 gate).
        "description": "OpenAI Whisper speech-to-text transcription (local inference) with word-level timestamps.",
        "type": "transcription",
        "category": "transcription",
        "interface": "cjm_transcription_plugin_system.plugin_interface.TranscriptionPlugin",
        
        "module": "cjm_transcription_plugin_whisper.plugin",
        "class": "WhisperLocalPlugin",
        
        # Critical: The absolute path to THIS environment's python
        "python_path": sys.executable,
        
        "db_path": db_path,
        
        # Phase 5a / CR-7 reframe: binary hard-facts only (quantitative amounts dropped, V12 gate).
        "resources": {
            "requires_gpu": True
        },
        
        # Track 19: CUDA_VISIBLE_DEVICES + OMP_NUM_THREADS + XDG_CACHE_HOME (templated)
        # are declared on the plugin class via WORKER_ENV; the substrate resolves +
        # injects them at spawn.
        "env_vars": {}
    }
