"""Metadata introspection for the Whisper plugin used by cjm-ctl to generate the registration manifest."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/meta.ipynb.

# %% auto 0
__all__ = ['get_plugin_metadata']

# %% ../nbs/meta.ipynb 3
import os
import sys
from typing import Any, Dict

# %% ../nbs/meta.ipynb 4
def get_plugin_metadata() -> Dict[str, Any]: # Plugin metadata for manifest generation
    """Return metadata required to register this plugin with the PluginManager."""
    # Fallback base path (current behavior for backward compatibility)
    base_path = os.path.dirname(os.path.dirname(sys.executable))

    # Use CJM config if available, else fallback to env-relative paths
    cjm_data_dir = os.environ.get("CJM_DATA_DIR")
    cjm_models_dir = os.environ.get("CJM_MODELS_DIR")

    # Plugin data directory
    plugin_name = "cjm-transcription-plugin-whisper"
    if cjm_data_dir:
        data_dir = os.path.join(cjm_data_dir, plugin_name)
    else:
        data_dir = os.path.join(base_path, "data")
    
    db_path = os.path.join(data_dir, "whisper_transcriptions.db")
    
    # Ensure data directory exists
    os.makedirs(data_dir, exist_ok=True)

    # Model cache: use models_dir if configured
    if cjm_models_dir:
        cache_home = os.path.join(cjm_models_dir, "whisper")
    else:
        cache_home = os.path.join(base_path, ".cache", "whisper")

    return {
        "name": plugin_name,
        "version": "1.0.0",
        "type": "transcription",
        "category": "transcription",
        "interface": "cjm_transcription_plugin_system.plugin_interface.TranscriptionPlugin",
        
        "module": "cjm_transcription_plugin_whisper.plugin",
        "class": "WhisperLocalPlugin",
        
        # Critical: The absolute path to THIS environment's python
        "python_path": sys.executable,
        
        "db_path": db_path,
        
        "resources": {
            "requires_gpu": True,
            "min_gpu_vram_mb": 4096,
            "recommended_gpu_vram_mb": 8192,
            "min_system_ram_mb": 8192
        },
        
        "env_vars": {
            "CUDA_VISIBLE_DEVICES": "0",  # Default, can be overridden by plugins.yaml
            "OMP_NUM_THREADS": "4",
            "XDG_CACHE_HOME": cache_home,
        }
    }
