"""Plugin implementation for OpenAI Whisper transcription

Docs: https://cj-mills.github.io/cjm-transcription-plugin-whisperplugin.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/plugin.ipynb.

# %% auto #0
__all__ = ['WhisperPluginConfig', 'WhisperLocalPlugin']

# %% ../nbs/plugin.ipynb #a37e28c1
import json
import os
import sys
from uuid import uuid4
import logging
from pathlib import Path
from dataclasses import dataclass, field
from typing import Dict, Any, Optional, List, Union, ClassVar
import warnings

import numpy as np
import torch
from fastcore.basics import patch

try:
    import whisper
    from whisper import load_model
    from whisper import transcribe
    from cjm_ffmpeg_utils.core import FFMPEG_AVAILABLE
    WHISPER_AVAILABLE = True and FFMPEG_AVAILABLE
except ImportError:
    WHISPER_AVAILABLE = False
    
from cjm_transcription_plugin_system.plugin_interface import TranscriptionPlugin
from cjm_transcription_plugin_system.core import TranscriptionResult
from cjm_transcription_plugin_system.storage import TranscriptionStorage
from cjm_plugin_system.utils.hashing import hash_file, hash_bytes, hash_dict_canonical
from cjm_plugin_system.core.interface import RELOAD_TRIGGER, EnvVarSpec
from cjm_plugin_system.core.errors import (
    PluginInputError, PluginFatalError,
)
from cjm_plugin_system.utils.validation import (
    dict_to_config, config_to_dict, validate_config, dataclass_to_jsonschema,
    SCHEMA_TITLE, SCHEMA_DESC, SCHEMA_MIN, SCHEMA_MAX, SCHEMA_ENUM
)

from cjm_transcription_plugin_whisper.meta import (
    get_plugin_metadata
)

# Shared torch helpers (cjm-torch-plugin-utils): release + CUDA-OOM typing + device resolution.
from cjm_torch_plugin_utils.memory import release_model
from cjm_torch_plugin_utils.oom import cuda_oom_to_plugin_resource_error
from cjm_torch_plugin_utils.device import resolve_torch_device

# %% ../nbs/plugin.ipynb #96534aec-1cd2-4f03-ac08-eb1137e37ee3
@dataclass
class WhisperPluginConfig:
    """Configuration for Whisper transcription plugin."""
    model:str = field(
        default="base",
        metadata={
            SCHEMA_TITLE: "Model",
            SCHEMA_DESC: "Whisper model size. Larger models are more accurate but slower.",
            SCHEMA_ENUM: ["tiny", "tiny.en", "base", "base.en", "small", "small.en", 
                        "medium", "medium.en", "large", "large-v1", "large-v2", "large-v3"],
            RELOAD_TRIGGER: "model",  # CR-4: model swap requires reload
        }
    )
    device:str = field(
        default="auto",
        metadata={
            SCHEMA_TITLE: "Device",
            SCHEMA_DESC: "Device for inference (auto will use CUDA if available)",
            SCHEMA_ENUM: ["auto", "cpu", "cuda"],
            RELOAD_TRIGGER: "model",  # CR-4: device change requires model reload
        }
    )
    language:Optional[str] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Language",
            SCHEMA_DESC: "Language code (e.g., 'en', 'es', 'fr') or None for auto-detection"
        }
    )
    task:str = field(
        default="transcribe",
        metadata={
            SCHEMA_TITLE: "Task",
            SCHEMA_DESC: "Task to perform (transcribe or translate to English)",
            SCHEMA_ENUM: ["transcribe", "translate"]
        }
    )
    temperature:float = field(
        default=0.0,
        metadata={
            SCHEMA_TITLE: "Temperature",
            SCHEMA_DESC: "Sampling temperature (0 for deterministic)",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 1.0
        }
    )
    temperature_increment_on_fallback:Optional[float] = field(
        default=0.2,
        metadata={
            SCHEMA_TITLE: "Temperature Increment",
            SCHEMA_DESC: "Temperature increment when falling back",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 1.0
        }
    )
    beam_size:int = field(
        default=5,
        metadata={
            SCHEMA_TITLE: "Beam Size",
            SCHEMA_DESC: "Beam search width",
            SCHEMA_MIN: 1,
            SCHEMA_MAX: 10
        }
    )
    best_of:int = field(
        default=5,
        metadata={
            SCHEMA_TITLE: "Best Of",
            SCHEMA_DESC: "Number of candidates when sampling",
            SCHEMA_MIN: 1,
            SCHEMA_MAX: 10
        }
    )
    patience:float = field(
        default=1.0,
        metadata={
            SCHEMA_TITLE: "Patience",
            SCHEMA_DESC: "Beam search patience factor",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 2.0
        }
    )
    length_penalty:Optional[float] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Length Penalty",
            SCHEMA_DESC: "Exponential length penalty"
        }
    )
    suppress_tokens:str = field(
        default="-1",
        metadata={
            SCHEMA_TITLE: "Suppress Tokens",
            SCHEMA_DESC: "Tokens to suppress ('-1' for default)"
        }
    )
    initial_prompt:Optional[str] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Initial Prompt",
            SCHEMA_DESC: "Optional initial prompt"
        }
    )
    condition_on_previous_text:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Condition on Previous",
            SCHEMA_DESC: "Condition on previous text"
        }
    )
    fp16:bool = field(
        default=True,
        metadata={
            SCHEMA_TITLE: "FP16",
            SCHEMA_DESC: "Use FP16 (half precision) for faster inference"
        }
    )
    compression_ratio_threshold:float = field(
        default=2.4,
        metadata={
            SCHEMA_TITLE: "Compression Ratio Threshold",
            SCHEMA_DESC: "Threshold for repetition detection",
            SCHEMA_MIN: 1.0,
            SCHEMA_MAX: 10.0
        }
    )
    logprob_threshold:float = field(
        default=-1.0,
        metadata={
            SCHEMA_TITLE: "Logprob Threshold",
            SCHEMA_DESC: "Average log probability threshold"
        }
    )
    no_speech_threshold:float = field(
        default=0.6,
        metadata={
            SCHEMA_TITLE: "No Speech Threshold",
            SCHEMA_DESC: "Threshold for silence detection",
            SCHEMA_MIN: 0.0,
            SCHEMA_MAX: 1.0
        }
    )
    word_timestamps:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Word Timestamps",
            SCHEMA_DESC: "Extract word-level timestamps"
        }
    )
    prepend_punctuations:str = field(
        default="\"'“¿([{-",
        metadata={
            SCHEMA_TITLE: "Prepend Punctuations",
            SCHEMA_DESC: "Punctuations to merge with next word"
        }
    )
    append_punctuations:str = field(
        default="\"'.。,，!！?？:：”)]}、",
        metadata={
            SCHEMA_TITLE: "Append Punctuations",
            SCHEMA_DESC: "Punctuations to merge with previous word"
        }
    )
    threads:int = field(
        default=0,
        metadata={
            SCHEMA_TITLE: "Threads",
            SCHEMA_DESC: "Number of threads (0 for default)",
            SCHEMA_MIN: 0
        }
    )
    model_dir:Optional[str] = field(
        default=None,
        metadata={
            SCHEMA_TITLE: "Model Directory",
            RELOAD_TRIGGER: "model",  # CR-4: changing model directory may require redownload + reload
            SCHEMA_DESC: "Directory to save/load models"
        }
    )
    compile_model:bool = field(
        default=False,
        metadata={
            SCHEMA_TITLE: "Compile Model",
            RELOAD_TRIGGER: "model",  # CR-4: torch.compile is one-shot; reload to apply
            SCHEMA_DESC: "Use torch.compile for potential speedup (requires PyTorch 2.0+)"
        }
    )

# %% ../nbs/plugin.ipynb #12e9f5c3
class WhisperLocalPlugin(TranscriptionPlugin):
    """OpenAI Whisper transcription plugin."""

    # CR-4: declarative reload-triggers — substrate's reconfigure_with_triggers
    # walks this config_class's dataclass fields for RELOAD_TRIGGER metadata and
    # fires the corresponding `_release_<trigger>` method on field changes.
    config_class = WhisperPluginConfig

    # Track 19 (CR-12 worker-env model): worker spawn env declared on the class.
    # CUDA_VISIBLE_DEVICES + OMP_NUM_THREADS are static; XDG_CACHE_HOME is templated to
    # the substrate models dir (Whisper stores downloaded weights under
    # <XDG_CACHE_HOME>/whisper). The substrate resolves + injects at Popen.
    WORKER_ENV: ClassVar[List[EnvVarSpec]] = [
        EnvVarSpec(
            name="CUDA_VISIBLE_DEVICES",
            default="0",
            label="GPU Device",
            description="Which GPU index the worker uses.",
        ),
        EnvVarSpec(
            name="OMP_NUM_THREADS",
            default="4",
            label="OpenMP Threads",
            description="Thread cap for CPU-side ops.",
        ),
        EnvVarSpec(
            name="XDG_CACHE_HOME",
            default="${CJM_MODELS_DIR}",
            label="Cache Home",
            description="XDG cache root; Whisper stores downloaded models under <XDG_CACHE_HOME>/whisper (templated to the substrate models dir).",
        ),
    ]
    
    def __init__(self):
        """Initialize the Whisper plugin with default configuration."""
        self.logger = logging.getLogger(f"{__name__}.{type(self).__name__}")
        self.config: WhisperPluginConfig = None
        self.model = None
        self.device = None
        self.model_dir = None
        self.storage: Optional[TranscriptionStorage] = None
    
    @property
    def name(self) -> str: # Plugin name identifier
        """Get the plugin name identifier."""
        return "whisper_local"
    
    @property
    def version(self) -> str: # Plugin version string
        """Get the plugin version string."""
        from cjm_transcription_plugin_whisper import __version__
        return __version__
    
    @property
    def supported_formats(self) -> List[str]: # List of supported audio file formats
        """Get the list of supported audio file formats."""
        return ["wav", "mp3", "flac", "m4a", "ogg", "webm", "mp4", "avi", "mov"]

    def get_current_config(self) -> Dict[str, Any]: # Current configuration as dictionary
        """Return current configuration state."""
        if not self.config:
            return {}
        return config_to_dict(self.config)

    def get_config_schema(self) -> Dict[str, Any]: # JSON Schema for configuration
        """Return JSON Schema for UI generation."""
        return dataclass_to_jsonschema(WhisperPluginConfig)

    @staticmethod
    def get_config_dataclass() -> WhisperPluginConfig: # Configuration dataclass
        """Return dataclass describing the plugin's configuration options."""
        return WhisperPluginConfig
    

    def initialize(
        self,
        config: Optional[Any] = None # Configuration dataclass, dict, or None
    ) -> None:
        """First-time setup. CR-4: the manual model/device diff-and-reload is replaced
        by declarative RELOAD_TRIGGER metadata; the substrate's reconfigure path fires
        _release_model then re-applies config via _apply_config."""
        self._apply_config(config)
        
        # Initialize standardized storage (one-time)
        db_path = get_plugin_metadata()["db_path"]
        self.storage = TranscriptionStorage(db_path)
        
        self.logger.info(f"Initialized Whisper plugin with model '{self.config.model}' on device '{self.device}'")
    
    
    
    
    def execute(
        self,
        audio: Union[str, Path], # Path to the audio file to transcribe
        **kwargs # Additional arguments to override config
    ) -> TranscriptionResult: # Transcription result with text and metadata
        """Transcribe audio using Whisper.

        `audio` is a path to a decodable audio file; the caller guarantees it is
        model-ready (format / sample-rate / channels handled upstream)."""
        # Validate + resolve the input path
        audio_path = self._prepare_audio(audio)

        # Hash the audio file (content) for the cache key
        audio_hash = hash_file(audio_path)

        # Hash the effective config for cache keying. CR-15: config_hash derives from
        # self.config (the effective config). The per-call kwargs config-overrides below
        # are NOT reflected here — that override path predates the substrate overhaul and
        # is slated for removal (see project_execute_invocation_contract_gap / candidate CR-15).
        config_hash = hash_dict_canonical(config_to_dict(self.config))

        # 1. Cache check (content-correct: audio_path + audio_hash + config_hash), before
        #    loading the model so a pure cache hit skips the model load entirely.
        if not kwargs.get("force", False):
            cached = self.storage.get_cached(str(audio), audio_hash, config_hash)
            if cached:
                self.logger.info(f"Using cached transcription for {audio}")
                return TranscriptionResult(
                    text=cached.text,
                    confidence=None,
                    segments=cached.segments,
                    metadata=cached.metadata,
                )

        # 2. Cache miss — load the model and transcribe
        self._load_model()

        # Get config values, allowing kwargs overrides
        # CR-15: these per-call config-overrides bypass reconfigure/persistence/validation/
        # config_hash and are slated for removal; provenance kwargs (job_id/source_*_time) stay.
        model_name = kwargs.get("model", self.config.model)
        task = kwargs.get("task", self.config.task)
        language = kwargs.get("language", self.config.language)
        beam_size = kwargs.get("beam_size", self.config.beam_size)
        best_of = kwargs.get("best_of", self.config.best_of)
        patience = kwargs.get("patience", self.config.patience)
        length_penalty = kwargs.get("length_penalty", self.config.length_penalty)
        suppress_tokens = kwargs.get("suppress_tokens", self.config.suppress_tokens)
        initial_prompt = kwargs.get("initial_prompt", self.config.initial_prompt)
        condition_on_previous_text = kwargs.get("condition_on_previous_text", self.config.condition_on_previous_text)
        fp16 = kwargs.get("fp16", self.config.fp16)
        compression_ratio_threshold = kwargs.get("compression_ratio_threshold", self.config.compression_ratio_threshold)
        logprob_threshold = kwargs.get("logprob_threshold", self.config.logprob_threshold)
        no_speech_threshold = kwargs.get("no_speech_threshold", self.config.no_speech_threshold)
        word_timestamps = kwargs.get("word_timestamps", self.config.word_timestamps)
        prepend_punctuations = kwargs.get("prepend_punctuations", self.config.prepend_punctuations)
        append_punctuations = kwargs.get("append_punctuations", self.config.append_punctuations)
        temperature = kwargs.get("temperature", self.config.temperature)
        temp_increment = kwargs.get("temperature_increment_on_fallback", self.config.temperature_increment_on_fallback)
        threads = kwargs.get("threads", self.config.threads)
        
        # Prepare Whisper arguments
        whisper_args = {
            "verbose": False,
            "task": task,
            "language": language,
            "beam_size": beam_size,
            "best_of": best_of,
            "patience": patience,
            "length_penalty": length_penalty,
            "suppress_tokens": suppress_tokens,
            "initial_prompt": initial_prompt,
            "condition_on_previous_text": condition_on_previous_text,
            "fp16": fp16 and self.device == "cuda",
            "compression_ratio_threshold": compression_ratio_threshold,
            "logprob_threshold": logprob_threshold,
            "no_speech_threshold": no_speech_threshold,
            "word_timestamps": word_timestamps,
            "prepend_punctuations": prepend_punctuations,
            "append_punctuations": append_punctuations,
        }
        
        # Handle temperature settings
        if temp_increment is not None and temp_increment > 0:
            temperature = tuple(np.arange(temperature, 1.0 + 1e-6, temp_increment))
        else:
            temperature = [temperature]
        
        # Set number of threads if specified
        if threads > 0:
            torch.set_num_threads(threads)
        
        # Perform transcription
        self.logger.info(f"Transcribing audio with Whisper {model_name}")
        
        try:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")  # Suppress Whisper warnings
                result = transcribe(
                    self.model,
                    audio_path,
                    temperature=temperature,
                    **whisper_args
                )
        except torch.cuda.OutOfMemoryError as e:
            # SG-47 Track B: CUDA OOM during Whisper inference -> typed PluginResourceError
            # (cjm-torch-plugin-utils); substrate's CR-7 reactive-retry reloads + retries.
            raise cuda_oom_to_plugin_resource_error(
                e, label=f"during Whisper inference (model={model_name!r})",
            ) from e
        
        # Process segments
        segments = []
        for segment in result.get("segments", []):
            segment_data = {
                "start": segment["start"],
                "end": segment["end"],
                "text": segment["text"].strip()
            }
            
            # Add word timestamps if available
            if "words" in segment and word_timestamps:
                segment_data["words"] = [
                    {
                        "word": word["word"],
                        "start": word["start"],
                        "end": word["end"],
                        "probability": word.get("probability")
                    }
                    for word in segment["words"]
                ]
            
            segments.append(segment_data)

        # Capture provenance metadata passed via kwargs
        provenance_meta = {
            k: v for k, v in kwargs.items() 
            if k in ['source_start_time', 'source_end_time']
        }
        
        # Create transcription result
        transcription_result = TranscriptionResult(
            text=result["text"].strip(),
            confidence=None,  # Whisper doesn't provide overall confidence
            segments=segments if segments else None,
            metadata={
                "model": model_name,
                **provenance_meta,
                "language": result.get("language", language),
                "task": task,
                "device": self.device,
                "duration": result.get("duration"),
            }
        )

        # Hash the transcription output
        text_hash = hash_bytes(transcription_result.text.encode())

        # Save to standardized storage (helper logs success/failure; never raises)
        job_id = kwargs.get("job_id", str(uuid4()))
        self.storage.save_with_logging(
            job_id=job_id,
            audio_path=str(audio),
            audio_hash=audio_hash,
            config_hash=config_hash,
            text=transcription_result.text,
            text_hash=text_hash,
            segments=transcription_result.segments,
            metadata=transcription_result.metadata,
            logger=self.logger,
        )
        
        self.logger.info(f"Transcription completed: {len(result['text'].split())} words")
        return transcription_result

# %% ../nbs/plugin.ipynb #m-apply-config
@patch
def _apply_config(
    self:WhisperLocalPlugin,
    config: Optional[Any] = None # Configuration dataclass, dict, or None
) -> None:
    """CR-4: apply config values + derive config-dependent state (device,
    model_dir). No heavy-resource work. Called by initialize (first-time) and by
    the substrate's reconfigure delta path. Model release on a model/device/
    model_dir/compile_model change is handled declaratively via RELOAD_TRIGGER
    -> _release_model (fired by the substrate BEFORE this re-applies config)."""
    self.config = dict_to_config(WhisperPluginConfig, config or {})

    # Resolve device ("auto" -> cuda if available, else cpu)
    self.device = resolve_torch_device(self.config.device)

    # Resolve model directory
    self.model_dir = self.config.model_dir

# %% ../nbs/plugin.ipynb #m-release-model
@patch
def _release_model(self:WhisperLocalPlugin) -> None:
    """CR-4: release the loaded model + free CUDA cache. RELOAD_TRIGGER target for
    model/device/model_dir/compile_model; on_disable / cleanup delegate here.
    Idempotent via cjm-torch-plugin-utils' release_model (no-op when already None)."""
    release_model(self, ["model"], device=self.device or "cpu", logger=self.logger)

# %% ../nbs/plugin.ipynb #m-load-model
@patch
def _load_model(self:WhisperLocalPlugin) -> None:
    """Load the Whisper model (lazy loading)."""
    if self.model is None:
        try:
            self.logger.info(f"Loading Whisper model: {self.config.model}")
            # Heartbeat wraps the WHOLE load: load_model downloads weights from the
            # Azure CDN via urllib on a cold cache (silent to the substrate's stall
            # detector), so the heartbeat keeps the (progress, message) tuple advancing.
            with self.heartbeat("loading Whisper model"):
                self.model = load_model(
                    self.config.model, 
                    device=self.device,
                    download_root=self.model_dir
                )

                # Optionally compile the model (PyTorch 2.0+)
                if self.config.compile_model and hasattr(torch, 'compile'):
                    self.model = torch.compile(self.model)
                    self.logger.info("Model compiled with torch.compile")

            self.logger.info("Local Whisper model loaded successfully")
        except torch.cuda.OutOfMemoryError as e:
            # SG-47 Track B: CUDA OOM during model load -> typed PluginResourceError
            # (cjm-torch-plugin-utils); substrate's CR-7 reactive-retry reloads + retries.
            raise cuda_oom_to_plugin_resource_error(
                e, label=f"loading Whisper model {self.config.model!r}",
            ) from e
        except Exception as e:
            # SG-47: non-resource load failures (missing model, corrupt download,
            # device misconfiguration) — fatal; author/config attention needed.
            raise PluginFatalError(f"Failed to load Whisper model: {e}") from e

# %% ../nbs/plugin.ipynb #m-prepare-audio
@patch
def _prepare_audio(
    self:WhisperLocalPlugin,
    audio: Union[str, Path] # Path to a decodable audio file
) -> str: # The audio file path
    """Validate the audio input and return it as a path string.

    The caller (orchestration / proxy) guarantees a model-ready audio file;
    in-memory preparation is no longer a plugin responsibility."""
    if isinstance(audio, (str, Path)):
        return str(audio)
    raise PluginInputError(  # SG-47: typed input-validation (multi-inherits ValueError)
        f"Unsupported audio input type: {type(audio)}; expected a file path (str or Path)",
        fields_invalid=["audio"],
    )

# %% ../nbs/plugin.ipynb #m-is-available
@patch
def is_available(self:WhisperLocalPlugin) -> bool: # True if Whisper and its dependencies are available
    """Check if Whisper is available."""
    return WHISPER_AVAILABLE

# %% ../nbs/plugin.ipynb #m-prefetch
@patch
def prefetch(self:WhisperLocalPlugin) -> None:
    """CR-4 (SG-19): eagerly load the model so the first execute() doesn't pay
    the download/load cost. Idempotent via _load_model's None-guard."""
    self._load_model()

# %% ../nbs/plugin.ipynb #m-on-disable
@patch
def on_disable(self:WhisperLocalPlugin) -> None:
    """CR-2: release the GPU model when the operator disables the plugin (the
    worker stays alive); lazy reload on the next execute after re-enable."""
    self._release_model()

# %% ../nbs/plugin.ipynb #m-cleanup
@patch
def cleanup(self:WhisperLocalPlugin) -> None:
    """Release resources on unload."""
    self._release_model()
    self.logger.info("Cleanup completed")
